language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
cache: cargo
script:
- cargo test --verbose --all-features
- (test $TRAVIS_RUST_VERSION != "nightly" || cargo bench)
