name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.31
    - run: cargo build --verbose
    - run: cargo build --verbose --all-features
    - run: cargo test --verbose
    - run: cargo test --verbose --all-features
